Tekno/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("home/", views.home, name="home"),
    path("products/", views.products, name="products"),
    path("login/", views.logmein, name="login"),
    path("signup/",views.signup, name="signup"),
    path("logout/", views.signout, name="logout"),
    path("signin/",views.signin,name="signin"),
    path("monitores/",views.monitores, name="monitores"),
    path("perifericos/", views.perifericos, name="perifericos"),
    path("pc_gaming/", views.pcs, name="pcs"),
    path("about/",views.about, name="about"),
    path("carrito/",views.carrito, name="carrito"),
    
]

carro/urls.py
from django.urls import path
from . import views

app_name = "carro"
urlpatterns = [

    path("guardar_carrito/", views.guardar_carrito, name="Save"),
    path('agregar/<int:producto_id>/', views.agregar_producto, name="Add"),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name="Del"),
    path('restar/<int:producto_id>/', views.restar_producto, name="Sub"),
    path('limpiar/', views.limpiar_carrito, name="CLS"),
    
]

myApp/urls.py
from django.contrib import admin
from django.urls import include, path
from Tekno import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.home),
    path("tekno/", include("Tekno.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("signup/",views.signup),
    path("signin/",views.signin),
    path("carro/", include("carro.urls")),
    path("pedidos/", include("pedidos.urls")),
]

pedidos/urls.py
from django.urls import path
from . import views

app_name = "pedido"
urlpatterns = [
    path("",views.procesar_pedido,name = "procesar_pedido"),
]

Tekno/models.py
from django.db import models
from django.contrib.auth.models import User

    
class Producto(models.Model):
    id_producto = models.AutoField(primary_key = True)
    nombre = models.CharField(max_length = 100,null = False)
    descripcion = models.TextField(blank=True)
    categoria = models.CharField(max_length = 100,null = False)
    tipo = models.CharField(max_length=100, null=False,default=False)
    stock = models.IntegerField(default="0")
    precio = models.FloatField(default = False, null = False)
    imagen = models.ImageField(upload_to="static/imagenes")
    
    def __str__(self):
        return self.nombre

Tekno/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from .models import Producto
from django.db.models import Q
from carro.carro import Cart



def home(request):
    carro = Cart(request)
    productos = Producto.objects.all()
    return render(request,"tekno/index.html",{
        "productos" : productos
    })


def products(request):
    return render(request,"tekno/gaming.html",{
        "errorNeedLogin" : "You must be logged in to view this site!"
    }) 

def logmein(request):

    if request.method == "GET":
        return render(request,"registration/login.html")
    else:
         pass

def signup(request):
    username = request.POST.get("username1")
    email = request.POST.get("email")
    nombre = request.POST.get("firstname")
    apellido = request.POST.get("lastname")
    password1 = request.POST.get("password1")
    password2 = request.POST.get("password2")
    if password1 == password2:
        try:
            user = User.objects.create_user(username = username,password = password1,email=email,first_name = nombre,last_name = apellido) 
            user.save()
            login(request,user)
            return redirect("home")
        except:
            return render(request,"registration/login.html",{
                "error" : "ERROR! : User already exists.",
                "alertUser" : "true"
            })
    else:
        return render(request,"registration/login.html",{
            "error" : "ERROR! Password does not match!",
            "alertPass" : "true",
        })
    
def signout(request):
    logout(request)
    return redirect("home")

def signin(request):
    if request.method == "GET":
        return render(request,"registration/signin.html")
    else:
        user = authenticate(request,username = request.POST["username1"],password = request.POST["password1"])
        if user is None:
            return render(request,"registration/signin.html",{
                "errorSignin" : "Username or password is incorrect.",
                "alertUser" : "true"
            })
        else:
            login(request,user)
            return redirect("home")

def monitores(request):
    busqueda = request.GET.get("buscar")
    productos = Producto.objects.all()
    print(busqueda)
    
    if busqueda:
        productos = Producto.objects.filter(
            Q(nombre__icontains = busqueda)
        ).distinct()
    return render(request,"tekno/monitores.html",{"productos" : productos})

def perifericos(request):
    busqueda = request.GET.get("buscar")
    productos = Producto.objects.all()
    
    if busqueda:
        productos = Producto.objects.filter(
            Q(nombre__icontains = busqueda) |
            Q(descripcion__icontains = busqueda)
        ).distinct()
    return render(request,"tekno/perifericos.html",{"productos" : productos})

def pcs(request):
    busqueda = request.GET.get("buscar")
    productos = Producto.objects.all()
    print(busqueda)
    
    if busqueda:
        productos = Producto.objects.filter(
            Q(nombre__icontains = busqueda)
        ).distinct()
    return render(request,"tekno/pcs.html",{"productos" : productos})

def about(request):
    return render(request,"tekno/about.html")


def carrito(request):
    return render(request,"tekno/carrito.html")

        

Tekno/templates/Tekno/about.html
{% extends "tekno/index.html" %}
{% load static %}
{% block content %}
<div class="container text-center">
    <div class="row">
        <div class="col">
            <img class="imagen" src="{% static 'imagenes/fotomario.jpg' %}" alt="">
            <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                  <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                      <strong>WHO WE ARE</strong>
                    </button>
                  </h2>
                  <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
                    <div class="accordion-body">
                      We are the <strong>BEST GAMING HARDWARE PROVIDER </strong>We look after your gaming <strong>needs. </strong><br>Even though there are <strong>tons </strong> of websites similar to us, we are still the best <strong>price</strong> you can find out there.
                    </div>
                  </div>
                </div>
    </div>
    <div class="progress">
      <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow= "75" aria-valuemin="0" aria-valuemax="100" style="width: 100% ;"></div>
    </div>
</div>
{% endblock %}

Tekno/templates/Tekno/carrito.html
{% extends 'tekno/index.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="alert alert-primary" role="alert">
        <table class="table table-bordered">
        <thead>
            <tr>
            <th scope="row" colspan="3" class="text-center">CARRITO</th>
            </tr>
            <tr>
            <th scope="col">NOMBRE</th>
            <th scope="col">PRECIO</th>
            <th scope="col">CANTIDAD</th>
            </tr>
        </thead>
        <tbody>
        {% if request.session.cart.items %}
        {% for key, value in request.session.cart.items %}
            <tr>
            <td>{{value.name}}</td>
            <td>{{value.price}}</td>
            <td>{{value.quantity}}
                <a href="{% url 'carro:Add' value.product_id %}" class="badge btn btn-dark badge-dark">+</a>
                <a href="{% url 'carro:Sub' value.product_id %}" class="badge btn btn-dark badge-dark">-</a>
            </td>
            </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">
                <div class="alert alert-danger text-center"> Sin Productos </div>
            </td>
        </tr>
        {% endif %}
            <tr>
            <th scope="row">Total:</th>
            <td colspan="2">$ {{total_carrito}}</td>
            </tr>
        </tbody>
        </table>
        <hr>
        </div>
        <div class="row text-center">
            <div class="col-4"><a href="{% url 'carro:CLS' %}" class="btn btn-danger">Limpiar</a></div>
            {% if request.session.cart.items %}
            <div class ="col-6"> <a href="{% url 'pedido:procesar_pedido' %}"class="btn btn-success">Crear pedido</a></a></div>
            {% endif %}
        </div>
    </div> 
{% endblock %}

Tekno/templates/Tekno/gaming.html
{% extends "tekno/index.html" %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <p class="gamingtitle text-center">
        ⚡THE BEST HARDWARE!⚡
    </p>
    <div class="rows justify-content-md-center">
        <div class="loco card col-md-2 text-center">
            <p class="titlegaming card-header">MONITORS</p>
            <div class="hola card-body">
            <h5 class="card-title">LET´S PLAY!</h5>
            <p class="card-subtitle text-muted">BECOME A PRO</p>
            </div>
            <a href="/tekno/monitores">
                <img class = "gamezone1" src="{% static 'imagenes/monitores.png' %}" width="200" height="200">
            </a>
            <div class="card-body">
            <p class="hola1 card-text text-center">The best hardware with the highest quality at the best PRICE.</p>
            </div>
            
        </div>
        <div class="loco card col-md-2 text-center">
            <p class="titlegaming card-header">PERIPHERALS</p>
            <div class="hola card-body">
            <h5 class="card-title">LET´S PLAY!</h5>
            <p class="card-subtitle text-muted">BECOME A PRO</p>
            </div>
            <a href="/tekno/perifericos">
                <img class = "gamezone1" src="{% static 'imagenes/perifericos.png' %}" width="200" height="200">
            </a>
            <div class="card-body">
            <p class="hola1 card-text text-center">The best peripherals for <strong>you</strong> to become the best!</p>
            </div>
        </div>
        <div class="loco card col-md-2 text-center">
            <p class="titlegaming card-header">GAMING PCS</p>
            <div class="hola card-body">
            <h5 class="card-title">LET´S PLAY!</h5>
            <p class="card-subtitle text-muted">BECOME A PRO</p>
            </div>
            <a href="/tekno/pc_gaming">
                <img class = "gamezone1" src="{% static 'imagenes/pc.png' %}" width="200" height="200">
            </a>
            <div class="card-body">
            <p class="hola1 card-text text-center">Already assembled PCs so you won´t worry about a thing.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Tekno/templates/Tekno/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tekno</title>
    <!-- ICONO -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'imagenes/icono2.ico' %}">
    <!-- CSS -->
    <link type="text/css" href="{% static 'css/home.css' %}" rel="stylesheet">
    
    <!-- LINK MODELO BOOTSWATCH -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.3.3/dist/vapor/bootstrap.min.css" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    <!-- GOOGLE FONTS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&family=Press+Start+2P&family=Workbench&display=swap" rel="stylesheet">
    <section class="wrapper">
      <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
      <div class="container-fluid">
        <div class="collapse navbar-collapse justify-content-center" id="navbarColor01">
          <a class="titulo navbar-brand" href="/tekno/home">Tekno</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <ul class="nav justify-content-center">
            <li class="nav-item">
              <a class="nav-link" href="/tekno/products">Products</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/tekno/about">About</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="/tekno/logout">Logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/tekno/carrito">
                <img src="{% static 'imagenes/carrito.png' %}" width="26" height="26">
              </a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="/tekno/signin">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/tekno/login">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/tekno/signin">
                <img src="{% static 'imagenes/carrito.png' %}" width="26" height="26">
              </a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a href="https://www.linkedin.com/in/mario-quevedo-blázquez-995a9b19a/">
                <img src="{% static 'imagenes/linkedin.png' %}" alt="" width="40" height="40">
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </section>
</head>
<body>
  
    {% block content %}
    <main class="container p-4">
      <p class="titleindex  text-center ">
          WELCOME TO TEKNO
      </p>
      <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow= "75" aria-valuemin="0" aria-valuemax="100" style="width: 100% ;"></div>
      </div>
      <a href="/tekno/products">  
        <img src="{% static 'imagenes/banner_inicio.png' %}">
      </a>
      {% if success == "false" %}
      <div class="alert alert-dismissible alert-success">
        <a href="/home/"></a>
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong> Registration successfully made! </strong> Welcome {{user}} <a href="#" class="alert-link">Visit your user panel here.</a>
        </div>
      {% endif %}
  </main>
  {% endblock %}  
</body>
<script
  src="https://code.jquery.com/jquery-3.7.1.slim.js"
  integrity="sha256-UgvvN8vBkgO0luPSUl2s8TIlOSYRoGFAX4jlCIm9Adc="
  crossorigin="anonymous"></script>
</html>

Tekno/templates/Tekno/monitores.html
{% extends "tekno/index.html" %}
{% load static %}
{% block content %}
<div class="container-fluid">
	<h1 class="gamingtitle">
		⚡THE GREATEST MONITORS!⚡
	</h1>
    <fieldset>
        <form class="buscadorgame d-flex" method="get">
            <input class="buscador form-control form-control-lg" name="buscar" type="search" placeholder="Search your monitors here!">
            <button class="buscador btn btn-secondary " type="submit">Search</button>
        </form>
    </fieldset>
	<p></p>  
    <div class="monitorrow row text-center">
		{% for producto in productos %}
		{% if producto.tipo == 'Monitor' %}		
		<div class="col-lg-4">
			<img class="monitores" style="border:5px solid #5cf0b2; padding:3px; margin:5px" src="{{producto.imagen.url}}" height="250" width="250">
			<div class="box-element product">
				<h4 class="nombremonitor"><strong>{{producto.nombre}}</strong></h4>
				<h6 class="nombremonitor">{{producto.descripcion}}</h6>
				{% if user.is_authenticated %}
				<button class="btn btn-outline-secondary add-btn" style="margin-top: 7px;">
					<a href="{% url 'carro:Add' producto.id_producto %}">Add to cart</a>
				</button>
				{% else %}
				<button class="btn btn-outline-secondary add-btn" style="margin-top: 7px;">
					<a href="/tekno/signin">Add to cart</a>
				</button>
				{% endif %}
				<h4 class="nombremonitor"><strong>{{producto.precio}}€</strong></h4>
				<h4 class="nombremonitor"><strong>Stock: {{producto.stock}} </strong></h4>
				<hr>
			</div>
		</div>
		{% endif %}
		{% endfor %}
	</div>
</div>
{% endblock %}

Tekno/templates/Tekno/pcs.html
{% extends "tekno/index.html" %}
{% load static %}
{% block content %}
<div class="container-fluid">
	<h1 class="gamingtitle">
		⚡THE BEST PCS FOR GAMING!⚡
	</h1>
    <fieldset>
        <form class="buscadorgame d-flex" method="get">
            <input class="buscador form-control form-control-lg" name="buscar" type="search" placeholder="Search your PCSs here!">
            <button class="buscador btn btn-secondary " type="submit">Search</button>
        </form>
    </fieldset>
	<p></p>  
    <div class="monitorrow row text-center">
		{% for producto in productos %}
		{% if producto.tipo == 'PC' %}		
		<div class="col-lg-4">
			<img class="monitores" style="border:5px solid #5cf0b2; padding:3px; margin:5px" src="{{producto.imagen.url}}" height="250" width="250">
			<div class="box-element product">
				<h4 class="nombremonitor"><strong>{{producto.nombre}}</strong></h4>
				<h6 class="nombremonitor">{{producto.descripcion}}</h6>
				{% if user.is_authenticated %}
				<button class="btn btn-outline-secondary add-btn" style="margin-top: 7px;">
					<a href="{% url 'carro:Add' producto.id_producto %}">Add to cart</a>
				</button>
				{% else %}
				<button class="btn btn-outline-secondary add-btn" style="margin-top: 7px;">
					<a href="/tekno/signin">Add to cart</a>
				</button>
				{% endif %}
				<h4 class="nombremonitor"><strong>{{producto.precio}}€</strong></h4>
				<h4 class="nombremonitor"><strong>Stock: {{producto.stock}} </strong></h4>
				<hr>
			</div>
		</div>
		{% endif %}
		{% endfor %}
	</div>
</div>
{% endblock %}

Tekno/templates/Tekno/perifericos.html
{% extends "tekno/index.html" %}
{% load static %}
{% block content %}
<div class="container-fluid">
	<h1 class="gamingtitle">
		⚡THE COOLEST PERIPHERALS!⚡
	</h1>
    <fieldset>
        <form class="buscadorgame d-flex" method="get">
            <input class="buscador form-control form-control-lg" name="buscar" type="search" placeholder="Search your peripherals here!">
            <button class="buscador btn btn-secondary " type="submit">Search</button>
        </form>
    </fieldset>
	<p></p>  
    <div class="monitorrow row text-center">
		{% for producto in productos %}
		{% if producto.tipo == 'Periferico' %}		
		<div class="col-lg-4">
			<img class="monitores" style="border:5px solid #5cf0b2; padding:3px; margin:5px" src="{{producto.imagen.url}}" height="250" width="250">
			<div class="box-element product">
				<h4 class="nombremonitor"><strong>{{producto.nombre}}</strong></h4>
				<h6 class="nombremonitor">{{producto.descripcion}}</h6>
				{% if user.is_authenticated %}
				<button class="btn btn-outline-secondary add-btn" style="margin-top: 7px;">
					<a href="{% url 'carro:Add' producto.id_producto %}">Add to cart</a>
				</button>
				{% else %}
				<button class="btn btn-outline-secondary add-btn" style="margin-top: 7px;">
					<a href="/tekno/signin">Add to cart</a>
				</button>
				{% endif %}
				<h4 class="nombremonitor"><strong>{{producto.precio}}€</strong></h4>
				<h4 class="nombremonitor"><strong>Stock: {{producto.stock}} </strong></h4>
				<hr>
			</div>
		</div>
		{% endif %}
		{% endfor %}
	</div>
</div>
{% endblock %}

Tekno/templates/Tekno/saludar1.html
{% extends "tekno/index.html" %}
{% load static %}

{% block content %}
<main class="container p-4">
            <h1 class="tituloLogin display-3 text-center sm-4 ">
                LOG-IN <br>/</br>REGISTER
            </h1>
            <div class="card-body">
                <div class="col-md-10 offset-md-1 my-auto">
                    <div class="card">
                        <div class="card-header">
            
                        </div>
                        <div class="card-body">
    
                        </div>
                    </div>
    
                </div>
    
            </div>
        </main>
{% endblock %}